server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:changeme}
    sources:
      youtube: false
      soundcloud: true
      twitch: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/

  level:
    lavalink: INFO

  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 30

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000